### ISSUE TITLE
Tagging System (5)

### ISSUE THREAD

**Issue by shaheinm** [openpracticelibrary/opl-content-api#10]
As a content api, I need a robust tagging system, so that I can deliver content in an intelligent way, and suggest further exploration of the library.

**ACCEPTANCE CRITERIA**

**Given** A request for a Practice
**When** I respond to a request for a Practice
**Then** Tags are available for query
**And** Tags are structured hierarchically

**Given** A request to add a tag to a Practice
**When** I respond to that request
**Then** The response will include a list of existing tags to use before creating a new one
**And** Duplicate tags are denied creation

**NOTES**
- There should be a mechanism for relationships between tags

**BLOCKERS**
None

**Comment by jameshbarton** [comment]
@shaheinm and I discussed this recently. We plan to keep the tagging mechanism simple by modeling tag hierarchy as multiple tags on the same practice, rather than building a hierarchy mechanism into the tag itself.

So for example, all practices involved with validation in the discovery section of the mobius loop could be tagged with "discovery" and "validation".  Then a simple search for the discovery tag would fetch all discovery practices, in validation and elsewhere.  A validation search would fetch only validation practices.

The only real tradeoff I can see is we could not have identical tags in different places of the hierarchy, for example, no validation tag under discovery and a separate validation tag in another part of the tag tree.  That seems a small price to pay for the simplicity of a single-namespace approach.

The tagging "system" then just becomes a set of basic GraphQL query components:
Create Tag
Get Practices by Tag Name
Associate Practice with Tag
Disassociate Practice from Tag

**Comment by jameshbarton** [comment]
@shaheinm @piyushsn - The tagging queries are all complete and have been tested interactively.  Per our conversation earlier today, I added a single practice-tag mutation that handles both associating and disassociating practices and tags.  See latest commit here:  https://github.com/openpracticelibrary/opl-fe/commits/tags

I'll start working on the unit tests only as we discussed, and then we can close this out.
