### ISSUE TITLE
Spike - Strapi Draft Capability

### ISSUE THREAD

**Issue by shaheinm** [openpracticelibrary/opl-content-api#39]

**Comment by haithamshahin333** [comment]
Minimal Versioning Capability for Practices:

- Create New ContentType called PracticeVersion
- Same Fields as Practice (title, body, etc.)
- Enum “Status” field (draft, published, archived)
- Relation back to Practice Type (may be null if brand new)
- Points below can be implemented using Lifecycle hooks  https://strapi.io/documentation/v3.x/concepts/models.html#lifecycle-hooks

Workflow 1 - Updating an Existing Practice

Example Practice ES: Event Storming:
{
ID: 123
Body: …
}

1. Update ES By submitting new body in form
- Make new PractiveVersion {ID: 1, Body: …, PracticeID: 123, Status: Draft}

2. Change status of PracticeVersion to Published
- Make current “published” PracticeVersion now “archived”
- Make “draft” to “published”
- Update Practice with PracticeVersion info

Workflow 2 - Create new Practice 

1. Create new PracticeVersion with no PracticeID {ID: 1, Body: …, PracticeID: null, Status: Draft}

2. Change status of PracticeVersion to Pubished
- Make “draft” to “published”
- Create Practice with PracticeVersion info
- Update PracticeVersion with Practice ID

**Comment by jameshbarton** [comment]
@haithamshahin333 - Some thoughts and questions on Versioning:

Does "minimal" mean we're targeting this for v1?  Assuming yes.  I also assume that's why there's no Review workflow laid out here, because we don't envision any pre-publication review for v1.  Right?  If so, have you thought through how this might extend to adding extra Review/Publication workflows with a new Curator role in the loop?

I assume this isn't using any of the new Strapi draft features that @shahein has mentioned. Looks like this is all our own custom stuff, right? (with the exception of leveraging lifecycle hooks)

I like the idea of using lifecycle hooks to help drive this process.

I assume we're not versioning any of the related objects associated with the Practice, right? For example, we wouldn't version the Tags for a Practice.

From a modeling standpoint, I go back and forth on my fondness for separation of Practice and PracticeVersion.  I'm not crazy about them both being fully materialized with lots of content copying required to maintain them.  I'd prefer something like Practice and PracticeContent.  PracticeContent would be fully materialized with separate copies of content for each document iteration, along with its workflow state.  Practice elements would contain 1:1 relationship with PracticeContent for all Published content.  That being said, keeping Practice fully materialized allows existing code to remain unchanged and might be more performant than adding a level of indirection between Practice and PracticeContent/Version.  So I talked myself back into your original proposal, but I did want to put the thought process out there.  I would consider changing name of PracticeVersion to something like PracticeContent - feels more descriptive to me.

Great Job on putting this together!

**Comment by haithamshahin333** [comment]
Appreciate the feedback greats points @jameshbarton . This was geared just with V1 in mind and assumes that all edits/new practices come from those who have access to Strapi (i.e. our team). 

I think it would be helpful though to discuss what we want this to look like in the longer term - maybe we can leverage this work in the future instead of needing a different versioning service.
